#!/usr/bin/env bash
# This script displays a list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY - BSD format
# Display in a user-oriented format - must have u flag
# Show process hierarchy- use -H flag

ps aux -H