#!/usr/bin/env bash
# This script stops 4-infinity_and_beyond process
var=$(pgrep bash -l | awk 'FNR == 3 {print $1}')
kill "$var"

# Option 2
#var=$(ps aux | grep "4-infinity_and_beyond | awk 'FNR == 1 {print $2}')
#kill "$var"
