#!/usr/bin/env bash
# This script catches SIGTERM signal and echoes, "I am invicible"
sig()
{
    echo "I am invicible!!!"
}
trap "sig" SIGTERM

while :
do
echo "To infinity and beyond"
sleep 2
#trap "sig" SIGTERM
done
