#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.

# Your script should only display:

# username
# user id
# Home directory path for the user

cut -d: -f1,4,6 /etc/passwd | while IFS= read -r line
do
    echo "$line"
done
