#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd using while loop + IFS

cat < /etc/passwd | while IFS=":" read -a line
do
   echo "The user ${line[0]} is part of the ${line[3]} gang,\
 lives in ${line[5]} and rides ${line[6]}.\
 ${line[2]} place is protected by the passcode ${line[1]},\
 more info about the user here: ${line[4]}"
done
