#!/usr/bin/env bash
# script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th
#loop iteration
x=1
while [ $x -le 20 ]
do
	if [ $x -eq 4 ]
	then
		printf "%s\nbad luck from China\n" $x
	elif [ $x -eq 9 ]
	then
		printf "%s\nbad luck from Japan\n" $x
	elif [ $x -eq 17 ]
	then
		printf "%s\nbad luck from Italy\n" $x
	else
		echo "$x"
	fi
	let x++
done
