#!/usr/bin/env bash
# script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th
#loop iteration
x=1
while [ $x -le 20 ]
do
    case $x in
	4)
	printf "%s\nbad luck from China\n" $x
	;;
	9)
	printf "%s\nbad luck from Japan\n" $x
	;;
	17)
	printf "%s\nbad luck from Italy\n" $x
	;;
	*)
	echo "$x"
	;;
	esac
	let x++
done
