#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
i=
list="$(ls)"
for i in $list
do
	cut -d- -f2 <<< "$i"
done
