#!/usr/bin/env bash
# Configures an Ubuntu server with:
# localhost resolves ot 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i '1 a\8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
